name: HAMC Server Java
description: Host a Java Minecraft server on Home Assistant
version: 1.0.4
slug: hamc-java
init: false
arch:
  - amd64
  - aarch64
  - armv7
ports:
  25565/tcp: "25565"
ports_description:
  25565/tcp: Minecraft Server Port
options:
  TYPE: VANILLA
  VERSION: LATEST
  SERVER_NAME: "HAMC Java Server"
  MOTD: "Greetings from Home Assistant"
  LEVEL: "World"
  GAMEMODE: survival
  DIFFICULTY: normal
  HARDCORE: false
  MAX_PLAYERS: 10
  WHITELIST: ""
  OPS: ""
  SPAWN_PROTECTION: 0
  PVP: true
  MAX_WORLD_SIZE: 29999984
  ALLOW_NETHER: true
  SEED: ""
  VIEW_DISTANCE: 10
  ONLINE_MODE: true
  MEMORY: 1G
  USE_AIKAR_FLAGS: true
  ANNOUNCE_PLAYER_ACHIEVEMENTS: true
  ENABLE_COMMAND_BLOCK: false
  FORCE_GAMEMODE: false
  WORLD: ""
  FORCE_WORLD_COPY: false
  PACKWIZ_URL: ""
schema:
  TYPE: str
  VERSION: str
  SERVER_NAME: str
  MOTD: str
  LEVEL: str
  GAMEMODE: list(survival|creative|adventure|spectator)
  DIFFICULTY: list(peaceful|easy|normal|hard)
  HARDCORE: bool
  MAX_PLAYERS: int
  WHITELIST: str
  OPS: str
  SPAWN_PROTECTION: int
  PVP: bool
  MAX_WORLD_SIZE: int
  ALLOW_NETHER: bool
  SEED: str
  VIEW_DISTANCE: int
  ONLINE_MODE: bool
  MEMORY: str
  USE_AIKAR_FLAGS: bool
  ANNOUNCE_PLAYER_ACHIEVEMENTS: bool
  ENABLE_COMMAND_BLOCK: bool
  FORCE_GAMEMODE: bool
  WORLD: str
  FORCE_WORLD_COPY: bool
  PACKWIZ_URL: str
map:
  - addons:rw
environment:
  EULA: "TRUE"
